// Code generated by pigeon; DO NOT EDIT.

package peg

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mussel-lox/clam/ast"
)

func matchedTextOf(c *current) string {
	return strings.TrimSpace(string(c.text))
}

var g = &grammar{
	rules: []*rule{
		{
			name:        "_",
			displayName: "\"WHITESPACES\"",
			pos:         position{line: 21, col: 1, offset: 378},
			expr: &zeroOrMoreExpr{
				pos: position{line: 21, col: 19, offset: 396},
				expr: &charClassMatcher{
					pos:        position{line: 21, col: 19, offset: 396},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "ALPHA",
			pos:  position{line: 23, col: 1, offset: 410},
			expr: &charClassMatcher{
				pos:        position{line: 23, col: 9, offset: 418},
				val:        "[a-zA-Z_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 24, col: 1, offset: 429},
			expr: &charClassMatcher{
				pos:        position{line: 24, col: 9, offset: 437},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "IDENTIFIER",
			pos:  position{line: 26, col: 1, offset: 446},
			expr: &actionExpr{
				pos: position{line: 26, col: 14, offset: 459},
				run: (*parser).callonIDENTIFIER1,
				expr: &seqExpr{
					pos: position{line: 26, col: 14, offset: 459},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 26, col: 14, offset: 459},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 16, offset: 461},
							name: "ALPHA",
						},
						&zeroOrMoreExpr{
							pos: position{line: 26, col: 22, offset: 467},
							expr: &choiceExpr{
								pos: position{line: 26, col: 24, offset: 469},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 26, col: 24, offset: 469},
										name: "ALPHA",
									},
									&ruleRefExpr{
										pos:  position{line: 26, col: 32, offset: 477},
										name: "DIGIT",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 41, offset: 486},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "STRING",
			pos:  position{line: 31, col: 1, offset: 556},
			expr: &actionExpr{
				pos: position{line: 31, col: 10, offset: 565},
				run: (*parser).callonSTRING1,
				expr: &seqExpr{
					pos: position{line: 31, col: 10, offset: 565},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 31, col: 10, offset: 565},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 31, col: 12, offset: 567},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 31, col: 16, offset: 571},
							expr: &charClassMatcher{
								pos:        position{line: 31, col: 16, offset: 571},
								val:        "[^\"]",
								chars:      []rune{'"'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&litMatcher{
							pos:        position{line: 31, col: 22, offset: 577},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 26, offset: 581},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "NUMBER",
			pos:  position{line: 36, col: 1, offset: 654},
			expr: &actionExpr{
				pos: position{line: 36, col: 10, offset: 663},
				run: (*parser).callonNUMBER1,
				expr: &seqExpr{
					pos: position{line: 36, col: 10, offset: 663},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 36, col: 10, offset: 663},
							name: "_",
						},
						&oneOrMoreExpr{
							pos: position{line: 36, col: 12, offset: 665},
							expr: &ruleRefExpr{
								pos:  position{line: 36, col: 12, offset: 665},
								name: "DIGIT",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 36, col: 19, offset: 672},
							expr: &seqExpr{
								pos: position{line: 36, col: 20, offset: 673},
								exprs: []any{
									&litMatcher{
										pos:        position{line: 36, col: 20, offset: 673},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 36, col: 24, offset: 677},
										expr: &ruleRefExpr{
											pos:  position{line: 36, col: 24, offset: 677},
											name: "DIGIT",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 36, col: 33, offset: 686},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "LEFT_PAREN",
			pos:  position{line: 45, col: 1, offset: 838},
			expr: &seqExpr{
				pos: position{line: 45, col: 17, offset: 854},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 45, col: 17, offset: 854},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 45, col: 19, offset: 856},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&ruleRefExpr{
						pos:  position{line: 45, col: 23, offset: 860},
						name: "_",
					},
				},
			},
		},
		{
			name: "RIGHT_PAREN",
			pos:  position{line: 46, col: 1, offset: 863},
			expr: &seqExpr{
				pos: position{line: 46, col: 17, offset: 879},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 46, col: 17, offset: 879},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 46, col: 19, offset: 881},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
					&ruleRefExpr{
						pos:  position{line: 46, col: 23, offset: 885},
						name: "_",
					},
				},
			},
		},
		{
			name: "LEFT_BRACE",
			pos:  position{line: 47, col: 1, offset: 888},
			expr: &seqExpr{
				pos: position{line: 47, col: 17, offset: 904},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 47, col: 17, offset: 904},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 47, col: 19, offset: 906},
						val:        "{",
						ignoreCase: false,
						want:       "\"{\"",
					},
					&ruleRefExpr{
						pos:  position{line: 47, col: 23, offset: 910},
						name: "_",
					},
				},
			},
		},
		{
			name: "RIGHT_BRACE",
			pos:  position{line: 48, col: 1, offset: 913},
			expr: &seqExpr{
				pos: position{line: 48, col: 17, offset: 929},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 48, col: 17, offset: 929},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 48, col: 19, offset: 931},
						val:        "}",
						ignoreCase: false,
						want:       "\"}\"",
					},
					&ruleRefExpr{
						pos:  position{line: 48, col: 23, offset: 935},
						name: "_",
					},
				},
			},
		},
		{
			name: "COMMA",
			pos:  position{line: 49, col: 1, offset: 938},
			expr: &seqExpr{
				pos: position{line: 49, col: 17, offset: 954},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 49, col: 17, offset: 954},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 49, col: 19, offset: 956},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 49, col: 23, offset: 960},
						name: "_",
					},
				},
			},
		},
		{
			name: "DOT",
			pos:  position{line: 50, col: 1, offset: 963},
			expr: &seqExpr{
				pos: position{line: 50, col: 17, offset: 979},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 50, col: 17, offset: 979},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 50, col: 19, offset: 981},
						val:        ".",
						ignoreCase: false,
						want:       "\".\"",
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 23, offset: 985},
						name: "_",
					},
				},
			},
		},
		{
			name: "MINUS",
			pos:  position{line: 51, col: 1, offset: 988},
			expr: &seqExpr{
				pos: position{line: 51, col: 17, offset: 1004},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 51, col: 17, offset: 1004},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 51, col: 19, offset: 1006},
						val:        "-",
						ignoreCase: false,
						want:       "\"-\"",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 23, offset: 1010},
						name: "_",
					},
				},
			},
		},
		{
			name: "PLUS",
			pos:  position{line: 52, col: 1, offset: 1013},
			expr: &seqExpr{
				pos: position{line: 52, col: 17, offset: 1029},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 52, col: 17, offset: 1029},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 52, col: 19, offset: 1031},
						val:        "+",
						ignoreCase: false,
						want:       "\"+\"",
					},
					&ruleRefExpr{
						pos:  position{line: 52, col: 23, offset: 1035},
						name: "_",
					},
				},
			},
		},
		{
			name: "SEMICOLON",
			pos:  position{line: 53, col: 1, offset: 1038},
			expr: &seqExpr{
				pos: position{line: 53, col: 17, offset: 1054},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 53, col: 17, offset: 1054},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 53, col: 19, offset: 1056},
						val:        ";",
						ignoreCase: false,
						want:       "\";\"",
					},
					&ruleRefExpr{
						pos:  position{line: 53, col: 23, offset: 1060},
						name: "_",
					},
				},
			},
		},
		{
			name: "SLASH",
			pos:  position{line: 54, col: 1, offset: 1063},
			expr: &seqExpr{
				pos: position{line: 54, col: 17, offset: 1079},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 54, col: 17, offset: 1079},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 54, col: 19, offset: 1081},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 23, offset: 1085},
						name: "_",
					},
				},
			},
		},
		{
			name: "STAR",
			pos:  position{line: 55, col: 1, offset: 1088},
			expr: &seqExpr{
				pos: position{line: 55, col: 17, offset: 1104},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 55, col: 17, offset: 1104},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 55, col: 19, offset: 1106},
						val:        "*",
						ignoreCase: false,
						want:       "\"*\"",
					},
					&ruleRefExpr{
						pos:  position{line: 55, col: 23, offset: 1110},
						name: "_",
					},
				},
			},
		},
		{
			name: "BANG",
			pos:  position{line: 56, col: 1, offset: 1113},
			expr: &seqExpr{
				pos: position{line: 56, col: 17, offset: 1129},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 56, col: 17, offset: 1129},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 56, col: 19, offset: 1131},
						val:        "!",
						ignoreCase: false,
						want:       "\"!\"",
					},
					&ruleRefExpr{
						pos:  position{line: 56, col: 23, offset: 1135},
						name: "_",
					},
				},
			},
		},
		{
			name: "EQUAL",
			pos:  position{line: 57, col: 1, offset: 1138},
			expr: &seqExpr{
				pos: position{line: 57, col: 17, offset: 1154},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 57, col: 17, offset: 1154},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 57, col: 19, offset: 1156},
						val:        "=",
						ignoreCase: false,
						want:       "\"=\"",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 23, offset: 1160},
						name: "_",
					},
				},
			},
		},
		{
			name: "GREATER",
			pos:  position{line: 58, col: 1, offset: 1163},
			expr: &seqExpr{
				pos: position{line: 58, col: 17, offset: 1179},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 58, col: 17, offset: 1179},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 58, col: 19, offset: 1181},
						val:        ">",
						ignoreCase: false,
						want:       "\">\"",
					},
					&ruleRefExpr{
						pos:  position{line: 58, col: 23, offset: 1185},
						name: "_",
					},
				},
			},
		},
		{
			name: "LESS",
			pos:  position{line: 59, col: 1, offset: 1188},
			expr: &seqExpr{
				pos: position{line: 59, col: 17, offset: 1204},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 59, col: 17, offset: 1204},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 59, col: 19, offset: 1206},
						val:        "<",
						ignoreCase: false,
						want:       "\"<\"",
					},
					&ruleRefExpr{
						pos:  position{line: 59, col: 23, offset: 1210},
						name: "_",
					},
				},
			},
		},
		{
			name: "BANG_EQUAL",
			pos:  position{line: 61, col: 1, offset: 1215},
			expr: &seqExpr{
				pos: position{line: 61, col: 17, offset: 1231},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 61, col: 17, offset: 1231},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 61, col: 19, offset: 1233},
						val:        "!=",
						ignoreCase: false,
						want:       "\"!=\"",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 24, offset: 1238},
						name: "_",
					},
				},
			},
		},
		{
			name: "EQUAL_EQUAL",
			pos:  position{line: 62, col: 1, offset: 1241},
			expr: &seqExpr{
				pos: position{line: 62, col: 17, offset: 1257},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 62, col: 17, offset: 1257},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 62, col: 19, offset: 1259},
						val:        "==",
						ignoreCase: false,
						want:       "\"==\"",
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 24, offset: 1264},
						name: "_",
					},
				},
			},
		},
		{
			name: "GREATER_EQUAL",
			pos:  position{line: 63, col: 1, offset: 1267},
			expr: &seqExpr{
				pos: position{line: 63, col: 17, offset: 1283},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 63, col: 17, offset: 1283},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 63, col: 19, offset: 1285},
						val:        ">=",
						ignoreCase: false,
						want:       "\">=\"",
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 24, offset: 1290},
						name: "_",
					},
				},
			},
		},
		{
			name: "LESS_EQUAL",
			pos:  position{line: 64, col: 1, offset: 1293},
			expr: &seqExpr{
				pos: position{line: 64, col: 17, offset: 1309},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 64, col: 17, offset: 1309},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 64, col: 19, offset: 1311},
						val:        "<=",
						ignoreCase: false,
						want:       "\"<=\"",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 24, offset: 1316},
						name: "_",
					},
				},
			},
		},
		{
			name: "AND",
			pos:  position{line: 66, col: 1, offset: 1321},
			expr: &seqExpr{
				pos: position{line: 66, col: 17, offset: 1337},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 66, col: 17, offset: 1337},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 66, col: 19, offset: 1339},
						val:        "and",
						ignoreCase: false,
						want:       "\"and\"",
					},
					&ruleRefExpr{
						pos:  position{line: 66, col: 28, offset: 1348},
						name: "_",
					},
				},
			},
		},
		{
			name: "CLASS",
			pos:  position{line: 67, col: 1, offset: 1351},
			expr: &seqExpr{
				pos: position{line: 67, col: 17, offset: 1367},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 67, col: 17, offset: 1367},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 67, col: 19, offset: 1369},
						val:        "class",
						ignoreCase: false,
						want:       "\"class\"",
					},
					&ruleRefExpr{
						pos:  position{line: 67, col: 28, offset: 1378},
						name: "_",
					},
				},
			},
		},
		{
			name: "ELSE",
			pos:  position{line: 68, col: 1, offset: 1381},
			expr: &seqExpr{
				pos: position{line: 68, col: 17, offset: 1397},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 68, col: 17, offset: 1397},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 68, col: 19, offset: 1399},
						val:        "else",
						ignoreCase: false,
						want:       "\"else\"",
					},
					&ruleRefExpr{
						pos:  position{line: 68, col: 28, offset: 1408},
						name: "_",
					},
				},
			},
		},
		{
			name: "FALSE",
			pos:  position{line: 69, col: 1, offset: 1411},
			expr: &seqExpr{
				pos: position{line: 69, col: 17, offset: 1427},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 69, col: 17, offset: 1427},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 69, col: 19, offset: 1429},
						val:        "false",
						ignoreCase: false,
						want:       "\"false\"",
					},
					&ruleRefExpr{
						pos:  position{line: 69, col: 28, offset: 1438},
						name: "_",
					},
				},
			},
		},
		{
			name: "FOR",
			pos:  position{line: 70, col: 1, offset: 1441},
			expr: &seqExpr{
				pos: position{line: 70, col: 17, offset: 1457},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 70, col: 17, offset: 1457},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 70, col: 19, offset: 1459},
						val:        "for",
						ignoreCase: false,
						want:       "\"for\"",
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 28, offset: 1468},
						name: "_",
					},
				},
			},
		},
		{
			name: "FUN",
			pos:  position{line: 71, col: 1, offset: 1471},
			expr: &seqExpr{
				pos: position{line: 71, col: 17, offset: 1487},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 71, col: 17, offset: 1487},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 71, col: 19, offset: 1489},
						val:        "fun",
						ignoreCase: false,
						want:       "\"fun\"",
					},
					&ruleRefExpr{
						pos:  position{line: 71, col: 28, offset: 1498},
						name: "_",
					},
				},
			},
		},
		{
			name: "IF",
			pos:  position{line: 72, col: 1, offset: 1501},
			expr: &seqExpr{
				pos: position{line: 72, col: 17, offset: 1517},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 72, col: 17, offset: 1517},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 72, col: 19, offset: 1519},
						val:        "if",
						ignoreCase: false,
						want:       "\"if\"",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 28, offset: 1528},
						name: "_",
					},
				},
			},
		},
		{
			name: "NIL",
			pos:  position{line: 73, col: 1, offset: 1531},
			expr: &seqExpr{
				pos: position{line: 73, col: 17, offset: 1547},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 73, col: 17, offset: 1547},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 73, col: 19, offset: 1549},
						val:        "nil",
						ignoreCase: false,
						want:       "\"nil\"",
					},
					&ruleRefExpr{
						pos:  position{line: 73, col: 28, offset: 1558},
						name: "_",
					},
				},
			},
		},
		{
			name: "OR",
			pos:  position{line: 74, col: 1, offset: 1561},
			expr: &seqExpr{
				pos: position{line: 74, col: 17, offset: 1577},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 74, col: 17, offset: 1577},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 74, col: 19, offset: 1579},
						val:        "or",
						ignoreCase: false,
						want:       "\"or\"",
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 28, offset: 1588},
						name: "_",
					},
				},
			},
		},
		{
			name: "PRINT",
			pos:  position{line: 75, col: 1, offset: 1591},
			expr: &seqExpr{
				pos: position{line: 75, col: 17, offset: 1607},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 75, col: 17, offset: 1607},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 75, col: 19, offset: 1609},
						val:        "print",
						ignoreCase: false,
						want:       "\"print\"",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 28, offset: 1618},
						name: "_",
					},
				},
			},
		},
		{
			name: "RETURN",
			pos:  position{line: 76, col: 1, offset: 1621},
			expr: &seqExpr{
				pos: position{line: 76, col: 17, offset: 1637},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 76, col: 17, offset: 1637},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 76, col: 19, offset: 1639},
						val:        "return",
						ignoreCase: false,
						want:       "\"return\"",
					},
					&ruleRefExpr{
						pos:  position{line: 76, col: 28, offset: 1648},
						name: "_",
					},
				},
			},
		},
		{
			name: "SUPER",
			pos:  position{line: 77, col: 1, offset: 1651},
			expr: &seqExpr{
				pos: position{line: 77, col: 17, offset: 1667},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 77, col: 17, offset: 1667},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 77, col: 19, offset: 1669},
						val:        "super",
						ignoreCase: false,
						want:       "\"super\"",
					},
					&ruleRefExpr{
						pos:  position{line: 77, col: 28, offset: 1678},
						name: "_",
					},
				},
			},
		},
		{
			name: "THIS",
			pos:  position{line: 78, col: 1, offset: 1681},
			expr: &seqExpr{
				pos: position{line: 78, col: 17, offset: 1697},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 78, col: 17, offset: 1697},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 78, col: 19, offset: 1699},
						val:        "this",
						ignoreCase: false,
						want:       "\"this\"",
					},
					&ruleRefExpr{
						pos:  position{line: 78, col: 28, offset: 1708},
						name: "_",
					},
				},
			},
		},
		{
			name: "TRUE",
			pos:  position{line: 79, col: 1, offset: 1711},
			expr: &seqExpr{
				pos: position{line: 79, col: 17, offset: 1727},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 79, col: 17, offset: 1727},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 79, col: 19, offset: 1729},
						val:        "true",
						ignoreCase: false,
						want:       "\"true\"",
					},
					&ruleRefExpr{
						pos:  position{line: 79, col: 28, offset: 1738},
						name: "_",
					},
				},
			},
		},
		{
			name: "VAR",
			pos:  position{line: 80, col: 1, offset: 1741},
			expr: &seqExpr{
				pos: position{line: 80, col: 17, offset: 1757},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 80, col: 17, offset: 1757},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 80, col: 19, offset: 1759},
						val:        "var",
						ignoreCase: false,
						want:       "\"var\"",
					},
					&ruleRefExpr{
						pos:  position{line: 80, col: 28, offset: 1768},
						name: "_",
					},
				},
			},
		},
		{
			name: "WHILE",
			pos:  position{line: 81, col: 1, offset: 1771},
			expr: &seqExpr{
				pos: position{line: 81, col: 17, offset: 1787},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 81, col: 17, offset: 1787},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 81, col: 19, offset: 1789},
						val:        "while",
						ignoreCase: false,
						want:       "\"while\"",
					},
					&ruleRefExpr{
						pos:  position{line: 81, col: 28, offset: 1798},
						name: "_",
					},
				},
			},
		},
	},
}

func (c *current) onIDENTIFIER1() (any, error) {

	str := matchedTextOf(c)
	return ast.Identifier(str), nil
}

func (p *parser) callonIDENTIFIER1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIDENTIFIER1()
}

func (c *current) onSTRING1() (any, error) {

	str := matchedTextOf(c)
	return ast.StringLiteral(str), nil
}

func (p *parser) callonSTRING1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSTRING1()
}

func (c *current) onNUMBER1() (any, error) {

	str := matchedTextOf(c)
	n, err := strconv.ParseFloat(str, 64)
	if err != nil {
		return nil, err
	}
	return ast.NumberLiteral(n), nil
}

func (p *parser) callonNUMBER1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNUMBER1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
